### ISSUE TITLE
Internal Server Error  The server encountered an internal error or misconfiguration and was unable to complete your request.

### ISSUE THREAD

**Issue by VwEl** [CHEATBEATER/bilibili-live-php#1]
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

by bilibili-live.php

**Comment by YunfengGao** [comment]
我这里尝试了一下，没有任何问题的。我猜可能是cookie的格式有问题？cookie的格式类似这种：DedeUserID=123456; DedeUserID__ckMd5=2c7e123c4321; ，可以直接在chrome里的调试模式下使用document.cookie去得，另外要把SESSDATA加进去。
