### ISSUE TITLE
不能自动送礼物

### ISSUE THREAD

**Issue by epicchaos** [CHEATBEATER/bilibili-live-php#2]
php bilibili-live.php 显示已送礼物 可是背包里面还是有礼物 还有个问题 执行 online.php和bilibili-live.php 显示得时间不同，bilibili-live.php显示的时间有问题

**Comment by YunfengGao** [comment]
不好意思，前一阵子准备毕业答辩，才看到。时间和送礼物的bug已经修复了。

**Comment by pwd0755** [comment]
感谢大大
新的脚本 运行还是出现问题 
php bilibili-live.php
PHP Parse error:  syntax error, unexpected ''11024'' (T_CONSTANT_ENCAPSED_STRING), expecting ')' in /var/www/bilibili-live.php on line 203

php online.php
PHP Parse error:  syntax error, unexpected '->' (T_OBJECT_OPERATOR) in /var/www/online.php on line 30
