### ISSUE TITLE
提示语法错误

### ISSUE THREAD

**Issue by epicchaos** [CHEATBEATER/bilibili-live-php#3]
新的脚本 运行还是出现问题
php bilibili-live.php
PHP Parse error: syntax error, unexpected ''11024'' (T_CONSTANT_ENCAPSED_STRING), expecting ')' in /var/www/bilibili-live.php on line 203

php online.php
PHP Parse error: syntax error, unexpected '->' (T_OBJECT_OPERATOR) in /var/www/online.php on line 30

**Comment by YunfengGao** [comment]
不好意思，cookie后面少了一个逗号，这回应该没问题了。

**Comment by epicchaos** [comment]
辛苦了 感谢 
很好奇参加小电视抽奖这个功能  怎么才能使用这功能？

**Comment by YunfengGao** [comment]
还没实现这个功能。。。
